--liquibase formatted sql
--changeset Bobrovich:create_houses_table
CREATE TABLE houses
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid    UUID                                    NOT NULL,
    city    VARCHAR(255)                            NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_houses PRIMARY KEY (id)
);

ALTER TABLE houses
    ADD CONSTRAINT uc_houses_uuid UNIQUE (uuid);

--liquibase formatted sql
--changeset Bobrovich:create_persons_table
CREATE TABLE persons
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID                                    NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    surname      VARCHAR(255)                            NOT NULL,
    residency_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

ALTER TABLE persons
    ADD CONSTRAINT uc_persons_uuid UNIQUE (uuid);

ALTER TABLE persons
    ADD CONSTRAINT FK_PERSONS_ON_RESIDENCY FOREIGN KEY (residency_id) REFERENCES houses (id);

--liquibase formatted sql
--changeset Bobrovich:create_houses_owners_table
CREATE TABLE houses_owners
(
    owned_houses_id BIGINT NOT NULL,
    owners_id       BIGINT NOT NULL
);

ALTER TABLE houses_owners
    ADD CONSTRAINT fk_houown_on_house FOREIGN KEY (owned_houses_id) REFERENCES houses (id);

ALTER TABLE houses_owners
    ADD CONSTRAINT fk_houown_on_person FOREIGN KEY (owners_id) REFERENCES persons (id);
